import "./globals.css";
import { TaskProvider } from "./server/TaskContext";
import { UserProvider } from "./server/userContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" />
        <UserProvider>
          <TaskProvider>{children}</TaskProvider>
        </UserProvider>
      </body>
    </html>
  );
}
